/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as StationsRouteImport } from './routes/stations'
import { Route as MoreRouteImport } from './routes/more'
import { Route as FillupsRouteImport } from './routes/fillups'
import { Route as CostsRouteImport } from './routes/costs'
import { Route as ChartsRouteImport } from './routes/charts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MoreVehiclesRouteImport } from './routes/more.vehicles'
import { Route as MoreFueltypesRouteImport } from './routes/more.fueltypes'
import { Route as MoreCalculatorRouteImport } from './routes/more.calculator'
import { Route as FillupsAddRouteImport } from './routes/fillups.add'

const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const StationsRoute = StationsRouteImport.update({
  id: '/stations',
  path: '/stations',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const FillupsRoute = FillupsRouteImport.update({
  id: '/fillups',
  path: '/fillups',
  getParentRoute: () => rootRouteImport,
} as any)
const CostsRoute = CostsRouteImport.update({
  id: '/costs',
  path: '/costs',
  getParentRoute: () => rootRouteImport,
} as any)
const ChartsRoute = ChartsRouteImport.update({
  id: '/charts',
  path: '/charts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreVehiclesRoute = MoreVehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => MoreRoute,
} as any)
const MoreFueltypesRoute = MoreFueltypesRouteImport.update({
  id: '/fueltypes',
  path: '/fueltypes',
  getParentRoute: () => MoreRoute,
} as any)
const MoreCalculatorRoute = MoreCalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => MoreRoute,
} as any)
const FillupsAddRoute = FillupsAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => FillupsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/charts': typeof ChartsRoute
  '/costs': typeof CostsRoute
  '/fillups': typeof FillupsRouteWithChildren
  '/more': typeof MoreRouteWithChildren
  '/stations': typeof StationsRoute
  '/stats': typeof StatsRoute
  '/fillups/add': typeof FillupsAddRoute
  '/more/calculator': typeof MoreCalculatorRoute
  '/more/fueltypes': typeof MoreFueltypesRoute
  '/more/vehicles': typeof MoreVehiclesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/charts': typeof ChartsRoute
  '/costs': typeof CostsRoute
  '/fillups': typeof FillupsRouteWithChildren
  '/more': typeof MoreRouteWithChildren
  '/stations': typeof StationsRoute
  '/stats': typeof StatsRoute
  '/fillups/add': typeof FillupsAddRoute
  '/more/calculator': typeof MoreCalculatorRoute
  '/more/fueltypes': typeof MoreFueltypesRoute
  '/more/vehicles': typeof MoreVehiclesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/charts': typeof ChartsRoute
  '/costs': typeof CostsRoute
  '/fillups': typeof FillupsRouteWithChildren
  '/more': typeof MoreRouteWithChildren
  '/stations': typeof StationsRoute
  '/stats': typeof StatsRoute
  '/fillups/add': typeof FillupsAddRoute
  '/more/calculator': typeof MoreCalculatorRoute
  '/more/fueltypes': typeof MoreFueltypesRoute
  '/more/vehicles': typeof MoreVehiclesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/charts'
    | '/costs'
    | '/fillups'
    | '/more'
    | '/stations'
    | '/stats'
    | '/fillups/add'
    | '/more/calculator'
    | '/more/fueltypes'
    | '/more/vehicles'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/charts'
    | '/costs'
    | '/fillups'
    | '/more'
    | '/stations'
    | '/stats'
    | '/fillups/add'
    | '/more/calculator'
    | '/more/fueltypes'
    | '/more/vehicles'
  id:
    | '__root__'
    | '/'
    | '/charts'
    | '/costs'
    | '/fillups'
    | '/more'
    | '/stations'
    | '/stats'
    | '/fillups/add'
    | '/more/calculator'
    | '/more/fueltypes'
    | '/more/vehicles'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChartsRoute: typeof ChartsRoute
  CostsRoute: typeof CostsRoute
  FillupsRoute: typeof FillupsRouteWithChildren
  MoreRoute: typeof MoreRouteWithChildren
  StationsRoute: typeof StationsRoute
  StatsRoute: typeof StatsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stations': {
      id: '/stations'
      path: '/stations'
      fullPath: '/stations'
      preLoaderRoute: typeof StationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fillups': {
      id: '/fillups'
      path: '/fillups'
      fullPath: '/fillups'
      preLoaderRoute: typeof FillupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/costs': {
      id: '/costs'
      path: '/costs'
      fullPath: '/costs'
      preLoaderRoute: typeof CostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charts': {
      id: '/charts'
      path: '/charts'
      fullPath: '/charts'
      preLoaderRoute: typeof ChartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more/vehicles': {
      id: '/more/vehicles'
      path: '/vehicles'
      fullPath: '/more/vehicles'
      preLoaderRoute: typeof MoreVehiclesRouteImport
      parentRoute: typeof MoreRoute
    }
    '/more/fueltypes': {
      id: '/more/fueltypes'
      path: '/fueltypes'
      fullPath: '/more/fueltypes'
      preLoaderRoute: typeof MoreFueltypesRouteImport
      parentRoute: typeof MoreRoute
    }
    '/more/calculator': {
      id: '/more/calculator'
      path: '/calculator'
      fullPath: '/more/calculator'
      preLoaderRoute: typeof MoreCalculatorRouteImport
      parentRoute: typeof MoreRoute
    }
    '/fillups/add': {
      id: '/fillups/add'
      path: '/add'
      fullPath: '/fillups/add'
      preLoaderRoute: typeof FillupsAddRouteImport
      parentRoute: typeof FillupsRoute
    }
  }
}

interface FillupsRouteChildren {
  FillupsAddRoute: typeof FillupsAddRoute
}

const FillupsRouteChildren: FillupsRouteChildren = {
  FillupsAddRoute: FillupsAddRoute,
}

const FillupsRouteWithChildren =
  FillupsRoute._addFileChildren(FillupsRouteChildren)

interface MoreRouteChildren {
  MoreCalculatorRoute: typeof MoreCalculatorRoute
  MoreFueltypesRoute: typeof MoreFueltypesRoute
  MoreVehiclesRoute: typeof MoreVehiclesRoute
}

const MoreRouteChildren: MoreRouteChildren = {
  MoreCalculatorRoute: MoreCalculatorRoute,
  MoreFueltypesRoute: MoreFueltypesRoute,
  MoreVehiclesRoute: MoreVehiclesRoute,
}

const MoreRouteWithChildren = MoreRoute._addFileChildren(MoreRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChartsRoute: ChartsRoute,
  CostsRoute: CostsRoute,
  FillupsRoute: FillupsRouteWithChildren,
  MoreRoute: MoreRouteWithChildren,
  StationsRoute: StationsRoute,
  StatsRoute: StatsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
